"""Generate visualisations of Burgers' equation solved with pardax and
predicted with a norax FNO.

Outputs:
    outputs/burgers_solve.gif: animated PDE solution (pardax)
    outputs/burgers_fno.png: FNO predictions vs ground truth (norax)

Usage:
    uv run examples/burgers1d/visualise.py
"""

import json
import pathlib
import sys

import equinox as eqx
import jax
import jax.numpy as jnp
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, PillowWriter

sys.path.insert(0, str(pathlib.Path(__file__).parent))

import pardax as pdx
from generate import GaussianField1D, advection, build_steppers, diffusion

import norax as nrx

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
MODEL_PATH = pathlib.Path(__file__).parent / "models" / "burgers1d_fno_256.eqx"
OUTPUT_DIR = pathlib.Path(__file__).parent / "figures"
OUTPUT_DIR.mkdir(exist_ok=True)

N = 256
L = 1.0
NU = 0.02
T_END = 1.0
STEP_SIZE = 1e-4
STEPS_PER_FRAME = 100  # Number of steps between saved frames
N_FRAMES = int(T_END / (STEP_SIZE * STEPS_PER_FRAME))
N_PRED_SAMPLES = 3  # Number of samples shown in FNO prediction figure

DTYPE = jnp.float32
DX = L / N
PARAMS = {"nu": NU, "dx": DX}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_model(path: pathlib.Path):
    with open(path, "rb") as f:
        hp = json.loads(f.readline().decode())
        hp["n_modes"] = tuple(hp["n_modes"])
        skeleton = nrx.FNO(key=jax.random.key(0), **hp)
        model = eqx.tree_deserialise_leaves(f, skeleton)
    return model, hp


def imex_step(carry, _):
    t, y, exp_st, imp_st = carry
    y_star, exp_st = exp_st(advection, t, y, STEP_SIZE, PARAMS)
    y_new, imp_st = imp_st(diffusion, t, y_star, STEP_SIZE, PARAMS)
    return (t + STEP_SIZE, y_new, exp_st, imp_st), None


@jax.jit
def solve(
    y0: jax.Array, exp_st: pdx.AbstractStepper, imp_st: pdx.AbstractStepper
):
    """Run the IMEX solver and return (t_frames, y_frames)."""

    def frame_step(carry, _):
        """Step to the next frame."""
        (t, y, e, i), _ = jax.lax.scan(
            imex_step, carry, length=STEPS_PER_FRAME
        )
        return (t, y, e, i), (t, y)

    _, (t_frames, y_frames) = jax.lax.scan(
        frame_step,
        (jnp.float32(0.0), y0, exp_st, imp_st),
        length=N_FRAMES,
    )
    return t_frames, y_frames


# ---------------------------------------------------------------------------
# GIF: animated PDE solution
# ---------------------------------------------------------------------------
print("Solving Burgers' equation to create GIF...")

# Use a seed far from the training seed (0) so no key-path overlap is
# possible with samples generated by generate.py.
key = jax.random.key(2**31 - 1)
grf = GaussianField1D(N, L)
x = np.linspace(0, L, num=N, endpoint=False, dtype=np.float32)

key, subkey = jax.random.split(key)
y0_gif = grf.sample(subkey)

exp_st, imp_st = build_steppers(NU, N, L)
t_frames, y_frames = solve(y0_gif, exp_st, imp_st)
t_frames = np.asarray(t_frames)
y_frames = np.asarray(y_frames)

print(
    f"  {N_FRAMES} frames computed (t in [{t_frames[0]:.3f}, {t_frames[-1]:.3f}])"
)

cmap_gif = cm.viridis  # type: ignore
norm_gif = plt.Normalize(vmin=0.0, vmax=T_END)  # type: ignore

fig_gif, ax_gif = plt.subplots(figsize=(7, 4), layout="tight")
ax_gif.set_xlim(0, L)
ymin, ymax = float(y_frames.min()) * 1.15, float(y_frames.max()) * 1.15
ax_gif.set_ylim(ymin, ymax)
ax_gif.set_xlabel("$x$")
ax_gif.set_ylabel("$u(t,\\, x)$")

# Show y0 as faint background
ax_gif.plot(
    x,
    np.asarray(y0_gif),
    color="grey",
    lw=1,
    alpha=0.4,
    ls="--",
    label="$u_0$",
)

(line_gif,) = ax_gif.plot([], [], lw=2)
time_text = ax_gif.text(
    0.02, 0.93, "", transform=ax_gif.transAxes, fontsize=10
)
ax_gif.legend(loc="upper right", fontsize=10)


def _init():
    line_gif.set_data([], [])
    time_text.set_text("")
    return line_gif, time_text


def _update(frame_idx):
    t = t_frames[frame_idx]
    line_gif.set_data(x, y_frames[frame_idx])
    line_gif.set_color(cmap_gif(norm_gif(t)))
    time_text.set_text(f"$t = {t:.2f}$")
    return line_gif, time_text


ani = FuncAnimation(
    fig_gif,
    _update,
    frames=N_FRAMES,
    init_func=_init,
    interval=40,
    blit=True,
)

gif_path = OUTPUT_DIR / "burgers_solve.gif"
ani.save(gif_path, writer=PillowWriter(fps=25))
plt.close(fig_gif)
print(f"  Saved to {gif_path}")

# ---------------------------------------------------------------------------
# Prediction image: FNO vs solver
# ---------------------------------------------------------------------------
print("Creating figure of FNO predictions...")

model, hyperparams = load_model(MODEL_PATH)
print(f"  Model hyperparameters: {hyperparams}")

fig_pred, axes = plt.subplots(
    1,
    N_PRED_SAMPLES,
    figsize=(4 * N_PRED_SAMPLES, 4),
    layout="tight",
    sharey=True,
)

for i, ax in enumerate(axes):
    key, subkey = jax.random.split(key)
    y0_i = grf.sample(subkey)

    # Ground truth: run the full solver to t=1
    exp_st_i, imp_st_i = build_steppers(NU, N, L)
    _, y_frames_i = solve(y0_i, exp_st_i, imp_st_i)
    y_truth = np.asarray(y_frames_i[-1])

    # FNO prediction
    input = jnp.stack([jnp.asarray(x), y0_i], axis=-1)
    prediction = np.asarray(model(input)).squeeze(-1)

    ax.plot(
        x,
        np.asarray(y0_i),
        color="steelblue",
        lw=1.5,
        alpha=0.6,
        label="$t = 0$",
        ls=":",
    )
    ax.plot(x, y_truth, color="black", lw=1.8, label="$t = 1$, solver")
    ax.plot(
        x,
        prediction,
        color="crimson",
        lw=1.5,
        ls="--",
        alpha=0.85,
        label="$t = 1$, FNO",
    )
    ax.set_xlabel("$x$")
    if i == 0:
        ax.set_ylabel("$u(x, t)$")
    if i == N_PRED_SAMPLES - 1:
        ax.legend(fontsize=10, loc="best")

    rel_err = float(
        jnp.linalg.norm(jnp.array(prediction) - jnp.array(y_truth))
        / jnp.linalg.norm(jnp.array(y_truth))
    )
    print(f"  Sample {i + 1}: relative L2 error = {rel_err:.4e}")

fig_pred.suptitle("1D Burgers' equation", fontsize=11)

pred_path = OUTPUT_DIR / "burgers_fno.png"
fig_pred.savefig(pred_path, dpi=150)
plt.close(fig_pred)
print(f"  Saved to {pred_path}")
